// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/address.dart';
import 'api/balance.dart';
import 'api/base_node.dart';
import 'api/db.dart';
import 'api/fee.dart';
import 'api/logger.dart';
import 'api/network.dart';
import 'api/scanner.dart';
import 'api/seeds.dart';
import 'api/send_transaction.dart';
import 'api/transactions.dart';
import 'api/utils.dart';
import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_SensitiveSeedsPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeedsPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  SensitiveSeeds
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  SensitiveSeeds
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  SensitiveSeeds
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  SensitiveSeeds
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  RustStreamSink<ScanEventDto> dco_decode_StreamSink_scan_event_dto_Sse(
      dynamic raw);

  @protected
  RustStreamSink<SendTransactionEvent>
      dco_decode_StreamSink_send_transaction_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AccountBalanceDto dco_decode_account_balance_dto(dynamic raw);

  @protected
  BlockchainInfoDto dco_decode_blockchain_info_dto(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  SensitiveSeeds
      dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  CounterpartyInfoDto dco_decode_box_autoadd_counterparty_info_dto(dynamic raw);

  @protected
  FeeInfoDto dco_decode_box_autoadd_fee_info_dto(dynamic raw);

  @protected
  LoggerConfig dco_decode_box_autoadd_logger_config(dynamic raw);

  @protected
  ScanConfiguration dco_decode_box_autoadd_scan_configuration(dynamic raw);

  @protected
  ScanStatusDto dco_decode_box_autoadd_scan_status_dto(dynamic raw);

  @protected
  SendTransactionDetails dco_decode_box_autoadd_send_transaction_details(
      dynamic raw);

  @protected
  TariNetwork dco_decode_box_autoadd_tari_network(dynamic raw);

  @protected
  TipInfo dco_decode_box_autoadd_tip_info(dynamic raw);

  @protected
  TransactionsReadyDto dco_decode_box_autoadd_transactions_ready_dto(
      dynamic raw);

  @protected
  TransactionsUpdatedDto dco_decode_box_autoadd_transactions_updated_dto(
      dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CounterpartyInfoDto dco_decode_counterparty_info_dto(dynamic raw);

  @protected
  DisplayedTransactionDirection dco_decode_displayed_transaction_direction(
      dynamic raw);

  @protected
  DisplayedTransactionDto dco_decode_displayed_transaction_dto(dynamic raw);

  @protected
  DisplayedTransactionSource dco_decode_displayed_transaction_source(
      dynamic raw);

  @protected
  DisplayedTransactionStatus dco_decode_displayed_transaction_status(
      dynamic raw);

  @protected
  FeeEstimate dco_decode_fee_estimate(dynamic raw);

  @protected
  FeeInfoDto dco_decode_fee_info_dto(dynamic raw);

  @protected
  FeePriority dco_decode_fee_priority(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DisplayedTransactionDto> dco_decode_list_displayed_transaction_dto(
      dynamic raw);

  @protected
  List<LogModuleConfig> dco_decode_list_log_module_config(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  LogModuleConfig dco_decode_log_module_config(dynamic raw);

  @protected
  LoggerConfig dco_decode_logger_config(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  SensitiveSeeds?
      dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          dynamic raw);

  @protected
  CounterpartyInfoDto? dco_decode_opt_box_autoadd_counterparty_info_dto(
      dynamic raw);

  @protected
  FeeInfoDto? dco_decode_opt_box_autoadd_fee_info_dto(dynamic raw);

  @protected
  LoggerConfig? dco_decode_opt_box_autoadd_logger_config(dynamic raw);

  @protected
  TariNetwork? dco_decode_opt_box_autoadd_tari_network(dynamic raw);

  @protected
  TipInfo? dco_decode_opt_box_autoadd_tip_info(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  ScanConfiguration dco_decode_scan_configuration(dynamic raw);

  @protected
  ScanEventDto dco_decode_scan_event_dto(dynamic raw);

  @protected
  ScanStatusDto dco_decode_scan_status_dto(dynamic raw);

  @protected
  SendTransactionDetails dco_decode_send_transaction_details(dynamic raw);

  @protected
  SendTransactionEvent dco_decode_send_transaction_event(dynamic raw);

  @protected
  TariNetwork dco_decode_tari_network(dynamic raw);

  @protected
  TipInfo dco_decode_tip_info(dynamic raw);

  @protected
  TransactionStage dco_decode_transaction_stage(dynamic raw);

  @protected
  TransactionsReadyDto dco_decode_transactions_ready_dto(dynamic raw);

  @protected
  TransactionsUpdatedDto dco_decode_transactions_updated_dto(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletCreationDetails dco_decode_wallet_creation_details(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  SensitiveSeeds
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  SensitiveSeeds
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  SensitiveSeeds
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  SensitiveSeeds
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<ScanEventDto> sse_decode_StreamSink_scan_event_dto_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<SendTransactionEvent>
      sse_decode_StreamSink_send_transaction_event_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AccountBalanceDto sse_decode_account_balance_dto(
      SseDeserializer deserializer);

  @protected
  BlockchainInfoDto sse_decode_blockchain_info_dto(
      SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  SensitiveSeeds
      sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  CounterpartyInfoDto sse_decode_box_autoadd_counterparty_info_dto(
      SseDeserializer deserializer);

  @protected
  FeeInfoDto sse_decode_box_autoadd_fee_info_dto(SseDeserializer deserializer);

  @protected
  LoggerConfig sse_decode_box_autoadd_logger_config(
      SseDeserializer deserializer);

  @protected
  ScanConfiguration sse_decode_box_autoadd_scan_configuration(
      SseDeserializer deserializer);

  @protected
  ScanStatusDto sse_decode_box_autoadd_scan_status_dto(
      SseDeserializer deserializer);

  @protected
  SendTransactionDetails sse_decode_box_autoadd_send_transaction_details(
      SseDeserializer deserializer);

  @protected
  TariNetwork sse_decode_box_autoadd_tari_network(SseDeserializer deserializer);

  @protected
  TipInfo sse_decode_box_autoadd_tip_info(SseDeserializer deserializer);

  @protected
  TransactionsReadyDto sse_decode_box_autoadd_transactions_ready_dto(
      SseDeserializer deserializer);

  @protected
  TransactionsUpdatedDto sse_decode_box_autoadd_transactions_updated_dto(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CounterpartyInfoDto sse_decode_counterparty_info_dto(
      SseDeserializer deserializer);

  @protected
  DisplayedTransactionDirection sse_decode_displayed_transaction_direction(
      SseDeserializer deserializer);

  @protected
  DisplayedTransactionDto sse_decode_displayed_transaction_dto(
      SseDeserializer deserializer);

  @protected
  DisplayedTransactionSource sse_decode_displayed_transaction_source(
      SseDeserializer deserializer);

  @protected
  DisplayedTransactionStatus sse_decode_displayed_transaction_status(
      SseDeserializer deserializer);

  @protected
  FeeEstimate sse_decode_fee_estimate(SseDeserializer deserializer);

  @protected
  FeeInfoDto sse_decode_fee_info_dto(SseDeserializer deserializer);

  @protected
  FeePriority sse_decode_fee_priority(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DisplayedTransactionDto> sse_decode_list_displayed_transaction_dto(
      SseDeserializer deserializer);

  @protected
  List<LogModuleConfig> sse_decode_list_log_module_config(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  LogModuleConfig sse_decode_log_module_config(SseDeserializer deserializer);

  @protected
  LoggerConfig sse_decode_logger_config(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  SensitiveSeeds?
      sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SseDeserializer deserializer);

  @protected
  CounterpartyInfoDto? sse_decode_opt_box_autoadd_counterparty_info_dto(
      SseDeserializer deserializer);

  @protected
  FeeInfoDto? sse_decode_opt_box_autoadd_fee_info_dto(
      SseDeserializer deserializer);

  @protected
  LoggerConfig? sse_decode_opt_box_autoadd_logger_config(
      SseDeserializer deserializer);

  @protected
  TariNetwork? sse_decode_opt_box_autoadd_tari_network(
      SseDeserializer deserializer);

  @protected
  TipInfo? sse_decode_opt_box_autoadd_tip_info(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ScanConfiguration sse_decode_scan_configuration(SseDeserializer deserializer);

  @protected
  ScanEventDto sse_decode_scan_event_dto(SseDeserializer deserializer);

  @protected
  ScanStatusDto sse_decode_scan_status_dto(SseDeserializer deserializer);

  @protected
  SendTransactionDetails sse_decode_send_transaction_details(
      SseDeserializer deserializer);

  @protected
  SendTransactionEvent sse_decode_send_transaction_event(
      SseDeserializer deserializer);

  @protected
  TariNetwork sse_decode_tari_network(SseDeserializer deserializer);

  @protected
  TipInfo sse_decode_tip_info(SseDeserializer deserializer);

  @protected
  TransactionStage sse_decode_transaction_stage(SseDeserializer deserializer);

  @protected
  TransactionsReadyDto sse_decode_transactions_ready_dto(
      SseDeserializer deserializer);

  @protected
  TransactionsUpdatedDto sse_decode_transactions_updated_dto(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletCreationDetails sse_decode_wallet_creation_details(
      SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_scan_event_dto_Sse(
      RustStreamSink<ScanEventDto> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_send_transaction_event_Sse(
      RustStreamSink<SendTransactionEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account_balance_dto(
      AccountBalanceDto self, SseSerializer serializer);

  @protected
  void sse_encode_blockchain_info_dto(
      BlockchainInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_counterparty_info_dto(
      CounterpartyInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_fee_info_dto(
      FeeInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_logger_config(
      LoggerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_scan_configuration(
      ScanConfiguration self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_scan_status_dto(
      ScanStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_send_transaction_details(
      SendTransactionDetails self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tari_network(
      TariNetwork self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tip_info(TipInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transactions_ready_dto(
      TransactionsReadyDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transactions_updated_dto(
      TransactionsUpdatedDto self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_counterparty_info_dto(
      CounterpartyInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_displayed_transaction_direction(
      DisplayedTransactionDirection self, SseSerializer serializer);

  @protected
  void sse_encode_displayed_transaction_dto(
      DisplayedTransactionDto self, SseSerializer serializer);

  @protected
  void sse_encode_displayed_transaction_source(
      DisplayedTransactionSource self, SseSerializer serializer);

  @protected
  void sse_encode_displayed_transaction_status(
      DisplayedTransactionStatus self, SseSerializer serializer);

  @protected
  void sse_encode_fee_estimate(FeeEstimate self, SseSerializer serializer);

  @protected
  void sse_encode_fee_info_dto(FeeInfoDto self, SseSerializer serializer);

  @protected
  void sse_encode_fee_priority(FeePriority self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_displayed_transaction_dto(
      List<DisplayedTransactionDto> self, SseSerializer serializer);

  @protected
  void sse_encode_list_log_module_config(
      List<LogModuleConfig> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_log_module_config(
      LogModuleConfig self, SseSerializer serializer);

  @protected
  void sse_encode_logger_config(LoggerConfig self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
      sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
          SensitiveSeeds? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_counterparty_info_dto(
      CounterpartyInfoDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_fee_info_dto(
      FeeInfoDto? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_logger_config(
      LoggerConfig? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tari_network(
      TariNetwork? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tip_info(
      TipInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_scan_configuration(
      ScanConfiguration self, SseSerializer serializer);

  @protected
  void sse_encode_scan_event_dto(ScanEventDto self, SseSerializer serializer);

  @protected
  void sse_encode_scan_status_dto(ScanStatusDto self, SseSerializer serializer);

  @protected
  void sse_encode_send_transaction_details(
      SendTransactionDetails self, SseSerializer serializer);

  @protected
  void sse_encode_send_transaction_event(
      SendTransactionEvent self, SseSerializer serializer);

  @protected
  void sse_encode_tari_network(TariNetwork self, SseSerializer serializer);

  @protected
  void sse_encode_tip_info(TipInfo self, SseSerializer serializer);

  @protected
  void sse_encode_transaction_stage(
      TransactionStage self, SseSerializer serializer);

  @protected
  void sse_encode_transactions_ready_dto(
      TransactionsReadyDto self, SseSerializer serializer);

  @protected
  void sse_encode_transactions_updated_dto(
      TransactionsUpdatedDto self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_creation_details(
      WalletCreationDetails self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeedsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_codegen_mock_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeedsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeedsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_codegen_mock_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeeds =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSensitiveSeedsPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
