// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Return the base58 Tari address of the wallet account named `wallet_name`.
///
/// `passphrase` (**secret**, optional) decrypts the account if needed; `network`
/// selects the network the address is encoded for (`None` → MainNet). Requires
/// [`initialize_database`](crate::api::db::initialize_database) first. Synchronous;
/// errors if the account does not exist.
Future<String> getAddress(
        {required String walletName,
        String? passphrase,
        TariNetwork? network}) =>
    RustLib.instance.api.crateApiAddressGetAddress(
        walletName: walletName, passphrase: passphrase, network: network);
