// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Read the balance of the wallet account named `wallet_name`.
///
/// Requires [`initialize_database`](crate::api::db::initialize_database) first.
/// Synchronous; errors if the account does not exist. Amounts are in microTari.
Future<AccountBalanceDto> getBalance({required String walletName}) =>
    RustLib.instance.api.crateApiBalanceGetBalance(walletName: walletName);

/// A wallet account's balance, all amounts in **microTari** (µT, 1e-6 XTM).
///
/// `total` is everything owned; `unconfirmed` is not yet confirmed;
/// `locked` is committed to in-flight spends; `available` is spendable now.
class AccountBalanceDto {
  final BigInt total;
  final BigInt unconfirmed;
  final BigInt locked;
  final BigInt available;

  const AccountBalanceDto({
    required this.total,
    required this.unconfirmed,
    required this.locked,
    required this.available,
  });

  @override
  int get hashCode =>
      total.hashCode ^
      unconfirmed.hashCode ^
      locked.hashCode ^
      available.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AccountBalanceDto &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          unconfirmed == other.unconfirmed &&
          locked == other.locked &&
          available == other.available;
}
