// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_tip_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Fetch the base node's current chain tip over HTTP RPC.
///
/// `base_url` is the base node RPC endpoint (e.g. `https://rpc.tari.com`).
/// Returns `Ok(None)` when the node reports no chain metadata yet; `Ok(Some(_))`
/// otherwise.
///
/// Async; performs network I/O. Errors if `base_url` cannot be parsed or the RPC
/// request fails. Part of the frozen public contract (ledger D2) even though it
/// has no explicit `#[frb]`: FRB v2 exports every `pub` item in `crate::api`.
Future<TipInfo?> getTipInfo({required String baseUrl}) =>
    RustLib.instance.api.crateApiBaseNodeGetTipInfo(baseUrl: baseUrl);

/// Report whether the base node at `base_url` considers itself synced to the
/// network tip.
///
/// `base_url` is the base node RPC endpoint. Returns the node's own `is_synced`
/// flag from its tip-info response.
///
/// Async; performs network I/O. Errors if `base_url` cannot be parsed or the RPC
/// request fails. Part of the frozen public contract (ledger D2) even though it
/// has no explicit `#[frb]`.
Future<bool> isNodeSynced({required String baseUrl}) =>
    RustLib.instance.api.crateApiBaseNodeIsNodeSynced(baseUrl: baseUrl);

/// Probe whether the base node at `base_url` is reachable (a `GET /get_tip_info`
/// round-trip succeeds). Liveness only, not sync status (use [`is_node_synced`]).
///
/// Returns `Ok(false)` — never `Err` — on parse failure, unreachable node, or
/// timeout, so Dart's `checkNodeHealth()` maps to a plain `bool`. Uses a short
/// timeout for snappy "test connection" UX. Errors only on client construction
/// failure. Part of the frozen public contract (ledger D2) even though it has no
/// explicit `#[frb]`.
Future<bool> checkNodeHealth({required String baseUrl}) =>
    RustLib.instance.api.crateApiBaseNodeCheckNodeHealth(baseUrl: baseUrl);

/// A snapshot of the base node's chain tip, as reported over its HTTP RPC.
///
/// Returned by [`get_tip_info`]. All heights are block counts and `timestamp`
/// is seconds since the Unix epoch.
class TipInfo {
  /// The height of the best (most recent) block in the chain.
  ///
  /// This is the number of blocks from the genesis block to the tip.
  final BigInt bestBlockHeight;

  /// The hash of the best block, as raw bytes.
  ///
  /// This uniquely identifies the current chain tip and can be used
  /// to detect chain reorganizations.
  final String bestBlockHash;

  /// The pruning horizon in blocks.
  ///
  /// Blocks older than `best_block_height - pruning_horizon` may have
  /// been pruned and their full data may not be available.
  final BigInt pruningHorizon;

  /// The height up to which the chain has been pruned.
  ///
  /// Block data below this height may not be fully available.
  final BigInt prunedHeight;

  /// The timestamp of the best block, in seconds since Unix epoch.
  final BigInt timestamp;

  const TipInfo({
    required this.bestBlockHeight,
    required this.bestBlockHash,
    required this.pruningHorizon,
    required this.prunedHeight,
    required this.timestamp,
  });

  @override
  int get hashCode =>
      bestBlockHeight.hashCode ^
      bestBlockHash.hashCode ^
      pruningHorizon.hashCode ^
      prunedHeight.hashCode ^
      timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TipInfo &&
          runtimeType == other.runtimeType &&
          bestBlockHeight == other.bestBlockHeight &&
          bestBlockHash == other.bestBlockHash &&
          pruningHorizon == other.pruningHorizon &&
          prunedHeight == other.prunedHeight &&
          timestamp == other.timestamp;
}
