// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `disconnect`, `get_db_connection`, `get_db_path`, `get_db_pool`, `init`, `with_current`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Database`

/// Open (or create) the wallet SQLite database at `path` and install it as the
/// process-global connection pool.
///
/// Must be called once before any DB-backed function (balance, transactions,
/// address, send, scan). Replaces any previously installed database. `path` is
/// the on-disk SQLite file path. Synchronous; errors if the pool cannot be
/// created.
Future<void> initializeDatabase({required String path}) =>
    RustLib.instance.api.crateApiDbInitializeDatabase(path: path);

/// Tear down the current wallet database, closing its connection pool.
///
/// Cooperatively cancels any in-flight scan first (so the scan stops issuing DB
/// queries before the pool is dropped), then clears the global slot. Idempotent:
/// calling it when no database is installed is a no-op. Synchronous.
Future<void> disconnectDatabase() =>
    RustLib.instance.api.crateApiDbDisconnectDatabase();
