// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`

/// Estimate the fee to send `amount` (in **microTari**) at the given `priority`.
///
/// `base_url` is the base node RPC endpoint and `wallet_name` selects the funding
/// account. Requires
/// [`initialize_database`](crate::api::db::initialize_database) first. Async;
/// performs network I/O. Errors if estimation fails or no estimate matches the
/// requested priority.
Future<FeeEstimate> estimateTransactionFee(
        {required BigInt amount,
        required FeePriority priority,
        required String baseUrl,
        required String walletName}) =>
    RustLib.instance.api.crateApiFeeEstimateTransactionFee(
        amount: amount,
        priority: priority,
        baseUrl: baseUrl,
        walletName: walletName);

/// A fee estimate for a prospective send.
///
/// `estimated_fee` and `total_amount_required` (amount + fee) are in **microTari**;
/// `fee_per_gram` is the rate in microTari per gram of transaction weight;
/// `input_count` is how many UTXOs would be spent.
class FeeEstimate {
  final BigInt estimatedFee;
  final BigInt totalAmountRequired;
  final BigInt feePerGram;
  final BigInt inputCount;

  const FeeEstimate({
    required this.estimatedFee,
    required this.totalAmountRequired,
    required this.feePerGram,
    required this.inputCount,
  });

  @override
  int get hashCode =>
      estimatedFee.hashCode ^
      totalAmountRequired.hashCode ^
      feePerGram.hashCode ^
      inputCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeEstimate &&
          runtimeType == other.runtimeType &&
          estimatedFee == other.estimatedFee &&
          totalAmountRequired == other.totalAmountRequired &&
          feePerGram == other.feePerGram &&
          inputCount == other.inputCount;
}

/// Desired confirmation speed for a transaction, trading fee against latency:
/// `Slow` (cheapest), `Medium`, or `Fast` (most expensive).
enum FeePriority {
  slow,
  medium,
  fast,
  ;
}
