// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KvTextVisitor`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `visit_pair`

/// Initialize the global logger, writing to a rotating file under `base_path/logs`
/// and to stdout, and install a panic hook that logs Rust panics.
///
/// `base_path` is the directory to create the `logs/` subfolder in; `config`
/// (`None` → sensible defaults) tunes levels and rotation. Call once at startup.
/// Synchronous (`#[frb(sync)]`); errors if the logger cannot be installed.
void initLogger({required String basePath, LoggerConfig? config}) =>
    RustLib.instance.api
        .crateApiLoggerInitLogger(basePath: basePath, config: config);

/// Logging verbosity, from `Error` (least) to `Trace` (most), or `Off`.
enum LogLevel {
  error,
  warn,
  info,
  debug,
  trace,
  off,
  ;
}

/// A per-module log-level override: log records whose `target` matches are
/// filtered at `level` instead of the default.
class LogModuleConfig {
  final String target;
  final LogLevel level;

  const LogModuleConfig({
    required this.target,
    required this.level,
  });

  @override
  int get hashCode => target.hashCode ^ level.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogModuleConfig &&
          runtimeType == other.runtimeType &&
          target == other.target &&
          level == other.level;
}

/// Configuration for [`init_logger`].
///
/// `default_level` applies to all modules without a `module_levels` override;
/// `max_file_size_mb` and `max_files` bound the rotating on-disk log.
class LoggerConfig {
  final LogLevel defaultLevel;
  final List<LogModuleConfig> moduleLevels;
  final BigInt maxFileSizeMb;
  final BigInt maxFiles;

  const LoggerConfig({
    required this.defaultLevel,
    required this.moduleLevels,
    required this.maxFileSizeMb,
    required this.maxFiles,
  });

  static Future<LoggerConfig> default_() =>
      RustLib.instance.api.crateApiLoggerLoggerConfigDefault();

  @override
  int get hashCode =>
      defaultLevel.hashCode ^
      moduleLevels.hashCode ^
      maxFileSizeMb.hashCode ^
      maxFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LoggerConfig &&
          runtimeType == other.runtimeType &&
          defaultLevel == other.defaultLevel &&
          moduleLevels == other.moduleLevels &&
          maxFileSizeMb == other.maxFileSizeMb &&
          maxFiles == other.maxFiles;
}
