// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_network`, `parse_network`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `from_str`, `from`

/// The Tari network a wallet/address/transaction targets.
///
/// Wherever a public function takes `Option<TariNetwork>`, `None` resolves to
/// `MainNet` (frozen behavior — ledger D3).
enum TariNetwork {
  mainNet,
  stageNet,
  nextNet,
  localNet,
  igor,
  esmeralda,
  ;
}
