// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'transactions.dart';
part 'scanner.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `cancel_active_scan`, `clear_scan_if_current`, `install_scan_controller`, `map_processing_event`, `run_forwarder`, `take_scan_controller`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ScanController`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `start_scan_with_handler`

/// Cancel the in-flight scan, if any.
///
/// Signals the current scan's cancellation token so the scan future and its event
/// forwarder wind down. A no-op when no scan is running. Synchronous; returns once
/// cancellation has been signalled (it does not block until the scan task exits).
Future<void> stopScan() => RustLib.instance.api.crateApiScannerStopScan();

/// Scan the blockchain for the wallet's transactions, streaming progress.
///
/// Streams [`ScanEventDto`]s over `sink` as blocks are scanned. With
/// `config.continuous` set, it keeps following the chain tip until cancelled via
/// [`stop_scan`]; starting a new scan supersedes any previous one (latest wins).
/// Requires [`initialize_database`] first.
///
/// Async and streamed. The scan **cancels when the Dart stream is closed** (a scan
/// with no listener has no useful work) — this deliberately differs from
/// [`send_transaction`](crate::api::send_transaction::send_transaction), which
/// continues. A scan failure emits a terminal [`ScanEventDto::Error`] and resolves
/// to `Err`.
Stream<ScanEventDto> startScan({required ScanConfiguration config}) =>
    RustLib.instance.api.crateApiScannerStartScan(config: config);

/// Inputs to [`start_scan`].
///
/// `wallet_name` selects the account; `passphrase` (**secret**) decrypts it;
/// `base_url` is the base node RPC endpoint; `batch_size` is the number of blocks
/// fetched per request; `continuous` keeps following the tip after catching up;
/// `poll_interval_seconds` is the wait between polls in continuous mode;
/// `required_confirmations` is the confirmation depth in blocks.
class ScanConfiguration {
  final String walletName;
  final String passphrase;
  final String baseUrl;
  final BigInt batchSize;
  final bool continuous;
  final BigInt pollIntervalSeconds;
  final BigInt requiredConfirmations;

  const ScanConfiguration({
    required this.walletName,
    required this.passphrase,
    required this.baseUrl,
    required this.batchSize,
    required this.continuous,
    required this.pollIntervalSeconds,
    required this.requiredConfirmations,
  });

  @override
  int get hashCode =>
      walletName.hashCode ^
      passphrase.hashCode ^
      baseUrl.hashCode ^
      batchSize.hashCode ^
      continuous.hashCode ^
      pollIntervalSeconds.hashCode ^
      requiredConfirmations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanConfiguration &&
          runtimeType == other.runtimeType &&
          walletName == other.walletName &&
          passphrase == other.passphrase &&
          baseUrl == other.baseUrl &&
          batchSize == other.batchSize &&
          continuous == other.continuous &&
          pollIntervalSeconds == other.pollIntervalSeconds &&
          requiredConfirmations == other.requiredConfirmations;
}

@freezed
sealed class ScanEventDto with _$ScanEventDto {
  const ScanEventDto._();

  const factory ScanEventDto.status(
    ScanStatusDto field0,
  ) = ScanEventDto_Status;
  const factory ScanEventDto.transactionsReady(
    TransactionsReadyDto field0,
  ) = ScanEventDto_TransactionsReady;
  const factory ScanEventDto.transactionsUpdated(
    TransactionsUpdatedDto field0,
  ) = ScanEventDto_TransactionsUpdated;
  const factory ScanEventDto.error(
    String field0,
  ) = ScanEventDto_Error;
}

@freezed
sealed class ScanStatusDto with _$ScanStatusDto {
  const ScanStatusDto._();

  const factory ScanStatusDto.started({
    required PlatformInt64 accountId,
    required BigInt fromHeight,
  }) = ScanStatusDto_Started;
  const factory ScanStatusDto.progress({
    required PlatformInt64 accountId,
    required BigInt currentHeight,
    required BigInt blocksScanned,
  }) = ScanStatusDto_Progress;
  const factory ScanStatusDto.completed({
    required PlatformInt64 accountId,
    required BigInt finalHeight,
    required BigInt totalBlocksScanned,
  }) = ScanStatusDto_Completed;
  const factory ScanStatusDto.paused({
    required PlatformInt64 accountId,
    required BigInt lastScannedHeight,
    required String reason,
  }) = ScanStatusDto_Paused;
  const factory ScanStatusDto.waiting({
    required PlatformInt64 accountId,
    required BigInt resumeInSeconds,
  }) = ScanStatusDto_Waiting;
  const factory ScanStatusDto.moreBlocksAvailable({
    required PlatformInt64 accountId,
    required BigInt lastScannedHeight,
  }) = ScanStatusDto_MoreBlocksAvailable;
}

/// Newly discovered transactions, carried inside
/// [`ScanEventDto::TransactionsReady`].
///
/// `block_height` is the block they were found at (when known); `is_initial_sync`
/// is `true` while catching up history versus live tip-following.
class TransactionsReadyDto {
  final PlatformInt64 accountId;
  final List<DisplayedTransactionDto> transactions;
  final BigInt? blockHeight;
  final bool isInitialSync;

  const TransactionsReadyDto({
    required this.accountId,
    required this.transactions,
    this.blockHeight,
    required this.isInitialSync,
  });

  @override
  int get hashCode =>
      accountId.hashCode ^
      transactions.hashCode ^
      blockHeight.hashCode ^
      isInitialSync.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionsReadyDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          transactions == other.transactions &&
          blockHeight == other.blockHeight &&
          isInitialSync == other.isInitialSync;
}

/// Status updates to already-known transactions (e.g. newly confirmed), carried
/// inside [`ScanEventDto::TransactionsUpdated`].
class TransactionsUpdatedDto {
  final PlatformInt64 accountId;
  final List<DisplayedTransactionDto> updatedTransactions;

  const TransactionsUpdatedDto({
    required this.accountId,
    required this.updatedTransactions,
  });

  @override
  int get hashCode => accountId.hashCode ^ updatedTransactions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionsUpdatedDto &&
          runtimeType == other.runtimeType &&
          accountId == other.accountId &&
          updatedTransactions == other.updatedTransactions;
}
