// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Return the full English BIP-39-style mnemonic word list.
///
/// Useful for client-side seed-word autocomplete/validation. Synchronous
/// (`#[frb(sync)]`); infallible. Returns static words, not wallet secrets.
List<String> listWords() => RustLib.instance.api.crateApiSeedsListWords();
