// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'transactions.dart';

// These functions are ignored because they are not marked as `pub`: `build_unsigned_transaction`, `create_transaction_sender`, `validate_inputs`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `send_transaction_with_handler`

/// Build, sign, and broadcast a one-sided transaction, streaming progress.
///
/// Streams a [`SendTransactionEvent`] for each [`TransactionStage`] over `sink`
/// and resolves to the broadcast [`DisplayedTransactionDto`]. `details` carries
/// the **secret** seed words/passphrase and the recipient/amount (in microTari).
/// Requires [`initialize_database`] first.
///
/// Async and streamed. The send **continues even if the Dart stream is closed**
/// (a half-broadcast transaction must finish) — this deliberately differs from
/// [`start_scan`](crate::api::scanner::start_scan), which cancels on a closed
/// sink. Errors propagate as the resolved `Err`.
Stream<SendTransactionEvent> sendTransaction(
        {required SendTransactionDetails details}) =>
    RustLib.instance.api
        .crateApiSendTransactionSendTransaction(details: details);

/// Inputs to [`send_transaction`].
///
/// `seed_words` (**secret**) and `passphrase` (**secret**) authorize spending.
/// `network` selects the Tari network (`None` → MainNet); `base_url` is the base
/// node RPC endpoint (`None` → the default mainnet RPC); `wallet_name` selects the
/// account; `recipient_address` is the recipient's base58 Tari address; `amount`
/// is in **microTari** (µT, 1e-6 XTM); `payment_id` is an optional tag;
/// `confirmation_window` is the required confirmations in blocks (`None` → 3).
class SendTransactionDetails {
  final List<String> seedWords;
  final String? passphrase;
  final TariNetwork? network;
  final String? baseUrl;
  final String walletName;
  final String recipientAddress;
  final BigInt amount;
  final String? paymentId;
  final BigInt? confirmationWindow;

  const SendTransactionDetails({
    required this.seedWords,
    this.passphrase,
    this.network,
    this.baseUrl,
    required this.walletName,
    required this.recipientAddress,
    required this.amount,
    this.paymentId,
    this.confirmationWindow,
  });

  @override
  int get hashCode =>
      seedWords.hashCode ^
      passphrase.hashCode ^
      network.hashCode ^
      baseUrl.hashCode ^
      walletName.hashCode ^
      recipientAddress.hashCode ^
      amount.hashCode ^
      paymentId.hashCode ^
      confirmationWindow.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransactionDetails &&
          runtimeType == other.runtimeType &&
          seedWords == other.seedWords &&
          passphrase == other.passphrase &&
          network == other.network &&
          baseUrl == other.baseUrl &&
          walletName == other.walletName &&
          recipientAddress == other.recipientAddress &&
          amount == other.amount &&
          paymentId == other.paymentId &&
          confirmationWindow == other.confirmationWindow;
}

/// A progress event streamed during [`send_transaction`]: the current
/// [`TransactionStage`] plus a human-readable `details` message.
class SendTransactionEvent {
  final TransactionStage stage;
  final String details;

  const SendTransactionEvent({
    required this.stage,
    required this.details,
  });

  @override
  int get hashCode => stage.hashCode ^ details.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SendTransactionEvent &&
          runtimeType == other.runtimeType &&
          stage == other.stage &&
          details == other.details;
}

/// The lifecycle stage of an in-flight send, carried on each
/// [`SendTransactionEvent`]. Emitted in order from `Initializing` to `Completed`.
enum TransactionStage {
  initializing,
  validatingInput,
  connectingToNetwork,
  fetchingBalance,
  constructingTransaction,
  signingKeyGeneration,
  signingTransaction,
  broadcasting,
  completed,
  ;
}
