// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Verify a `"<signature_hex>|<public_nonce_hex>"` signature over `message` against
/// the public spend key in the base58 Tari `address`.
///
/// Stateless: no database, loaded wallet, or network. Returns `Ok(false)` for a
/// well-formed-but-wrong signature; errors only on malformed input (bad address,
/// wrong signature format, or undecodable hex components).
Future<bool> verifyMessage(
        {required String message,
        required String signature,
        required String address}) =>
    RustLib.instance.api.crateApiSigningVerifyMessage(
        message: message, signature: signature, address: address);

/// Sign `message` with the wallet's spend secret, returning a domain-separated
/// Ristretto Schnorr signature as `"<signature_hex>|<public_nonce_hex>"`.
///
/// Off-chain: no node, fee, or transaction — nothing is broadcast. The spend secret
/// is derived from the 24-word `seed_words` via the same factory used by wallet
/// creation and `send_transaction`, so it matches the spend key in the wallet's
/// published address. View-only wallets have no mnemonic and cannot sign (guarded
/// Dart-side); an invalid word list errors as `Invalid Seed Words`.
Future<String> signMessage(
        {required String message, required List<String> seedWords}) =>
    RustLib.instance.api
        .crateApiSigningSignMessage(message: message, seedWords: seedWords);
