// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// List a page of the wallet's transactions, most recent first.
///
/// `limit`/`offset` paginate the result. Requires
/// [`initialize_database`](crate::api::db::initialize_database) first.
/// Synchronous; errors if the account does not exist.
Future<List<DisplayedTransactionDto>> getTransactions(
        {required String walletName,
        required PlatformInt64 limit,
        required PlatformInt64 offset}) =>
    RustLib.instance.api.crateApiTransactionsGetTransactions(
        walletName: walletName, limit: limit, offset: offset);

/// Where a transaction sits on chain: `block_height`, a formatted `timestamp`
/// string, and the number of `confirmations` (blocks) on top of it.
class BlockchainInfoDto {
  final BigInt blockHeight;
  final String timestamp;
  final BigInt confirmations;

  const BlockchainInfoDto({
    required this.blockHeight,
    required this.timestamp,
    required this.confirmations,
  });

  @override
  int get hashCode =>
      blockHeight.hashCode ^ timestamp.hashCode ^ confirmations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BlockchainInfoDto &&
          runtimeType == other.runtimeType &&
          blockHeight == other.blockHeight &&
          timestamp == other.timestamp &&
          confirmations == other.confirmations;
}

/// The other party to a transaction: their base58 `address` and the same
/// address rendered as an `address_emoji` string.
class CounterpartyInfoDto {
  final String address;
  final String addressEmoji;

  const CounterpartyInfoDto({
    required this.address,
    required this.addressEmoji,
  });

  @override
  int get hashCode => address.hashCode ^ addressEmoji.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CounterpartyInfoDto &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          addressEmoji == other.addressEmoji;
}

/// Whether a transaction credited (`Incoming`) or debited (`Outgoing`) the wallet.
enum DisplayedTransactionDirection {
  incoming,
  outgoing,
  ;
}

/// A transaction as displayed in the wallet UI.
///
/// `amount` is in **microTari** with a pre-formatted `amount_display`. `counterparty`
/// and `fee` are absent for some kinds. `payrefs` are hex payment-reference hashes.
class DisplayedTransactionDto {
  final String id;
  final DisplayedTransactionDirection direction;
  final DisplayedTransactionSource source;
  final DisplayedTransactionStatus status;
  final BigInt amount;
  final String amountDisplay;
  final String? message;
  final CounterpartyInfoDto? counterparty;
  final BlockchainInfoDto blockchain;
  final FeeInfoDto? fee;
  final List<String> payrefs;

  const DisplayedTransactionDto({
    required this.id,
    required this.direction,
    required this.source,
    required this.status,
    required this.amount,
    required this.amountDisplay,
    this.message,
    this.counterparty,
    required this.blockchain,
    this.fee,
    required this.payrefs,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      direction.hashCode ^
      source.hashCode ^
      status.hashCode ^
      amount.hashCode ^
      amountDisplay.hashCode ^
      message.hashCode ^
      counterparty.hashCode ^
      blockchain.hashCode ^
      fee.hashCode ^
      payrefs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DisplayedTransactionDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          direction == other.direction &&
          source == other.source &&
          status == other.status &&
          amount == other.amount &&
          amountDisplay == other.amountDisplay &&
          message == other.message &&
          counterparty == other.counterparty &&
          blockchain == other.blockchain &&
          fee == other.fee &&
          payrefs == other.payrefs;
}

/// How a transaction originated: a regular `Transfer`, mining `Coinbase`,
/// `OneSided` payment, or `Unknown`.
enum DisplayedTransactionSource {
  transfer,
  coinbase,
  oneSided,
  unknown,
  ;
}

/// The display status of a transaction as shown in the wallet UI.
enum DisplayedTransactionStatus {
  pending,
  unconfirmed,
  confirmed,
  cancelled,
  reorganized,
  rejected,
  locked,
  ;
}

/// Fee charged on a transaction: `amount` in **microTari** plus a pre-formatted
/// `amount_display` string for the UI.
class FeeInfoDto {
  final BigInt amount;
  final String amountDisplay;

  const FeeInfoDto({
    required this.amount,
    required this.amountDisplay,
  });

  @override
  int get hashCode => amount.hashCode ^ amountDisplay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FeeInfoDto &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          amountDisplay == other.amountDisplay;
}
