// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_creation_details`, `generate_details_from_seed`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `drop`, `fmt`, `zeroize`

/// Create a brand-new wallet from a freshly generated random cipher seed.
///
/// `wallet_name` names the account in the DB; `network` selects the Tari network
/// (`None` resolves to MainNet — frozen behavior); `passphrase` (**secret**)
/// encrypts the wallet at rest. Requires [`initialize_database`] first.
/// Returns the new wallet's address, keys, and freshly generated seed words.
/// Synchronous.
Future<WalletCreationDetails> createWallet(
        {required String walletName,
        TariNetwork? network,
        required String passphrase}) =>
    RustLib.instance.api.crateApiWalletCreateWallet(
        walletName: walletName, network: network, passphrase: passphrase);

/// Restore an existing wallet from its BIP-39-style seed words.
///
/// `seed_words` (**secret**) is the mnemonic to restore from; `passphrase`
/// (**secret**) re-encrypts the restored wallet; `network` selects the network
/// (`None` → MainNet). Requires [`initialize_database`] first. Returns the
/// restored wallet's address, keys, and seed words. Synchronous; errors on
/// invalid seed words.
Future<WalletCreationDetails> restoreWallet(
        {required String walletName,
        required List<String> seedWords,
        required String passphrase,
        TariNetwork? network}) =>
    RustLib.instance.api.crateApiWalletRestoreWallet(
        walletName: walletName,
        seedWords: seedWords,
        passphrase: passphrase,
        network: network);

/// Import a view-only wallet from a view private key and spend public key.
///
/// A view-only wallet can see incoming funds but cannot spend. `view_private_key_hex`
/// (**secret**) and `spend_public_key_hex` are hex-encoded keys; `birthday` is the
/// scan start epoch; `passphrase` (**secret**) encrypts the wallet; `network`
/// selects the network (`None` → MainNet). Requires [`initialize_database`] first.
/// The returned `seed_words` is always `None`. Synchronous; errors on invalid hex.
Future<WalletCreationDetails> importViewOnlyWallet(
        {required String walletName,
        required String viewPrivateKeyHex,
        required String spendPublicKeyHex,
        required int birthday,
        required String passphrase,
        TariNetwork? network}) =>
    RustLib.instance.api.crateApiWalletImportViewOnlyWallet(
        walletName: walletName,
        viewPrivateKeyHex: viewPrivateKeyHex,
        spendPublicKeyHex: spendPublicKeyHex,
        birthday: birthday,
        passphrase: passphrase,
        network: network);

/// Recover the seed words of the currently stored wallet.
///
/// `password` (**secret**) is the wallet's encryption passphrase, required to
/// decrypt the stored cipher seed. Returns a **secret**, zeroize-on-drop
/// [`SensitiveSeeds`] handle; call [`reveal_seed_words`] to read the words.
/// Requires [`initialize_database`] first. Synchronous; errors if there is no
/// account or no seed words (e.g. a view-only wallet).
Future<SensitiveSeeds> getSeedWords({required String password}) =>
    RustLib.instance.api.crateApiWalletGetSeedWords(password: password);

/// Explicitly read the seed words out of an opaque [`SensitiveSeeds`] handle.
///
/// This is the only way to move the **secret** words across the bridge as plain
/// strings — callers opt in deliberately. Synchronous; infallible.
Future<List<String>> revealSeedWords({required SensitiveSeeds handle}) =>
    RustLib.instance.api.crateApiWalletRevealSeedWords(handle: handle);

/// Delete the wallet account named `wallet_name` from the database.
///
/// Requires [`initialize_database`] first. Synchronous; errors if the delete
/// fails.
Future<void> deleteWallet({required String walletName}) =>
    RustLib.instance.api.crateApiWalletDeleteWallet(walletName: walletName);

/// List the friendly names of every wallet account in the database.
///
/// Requires [`initialize_database`] first. Synchronous.
Future<List<String>> listWallets() =>
    RustLib.instance.api.crateApiWalletListWallets();

/// Rename a wallet account from `current_wallet_name` to `new_wallet_name`.
///
/// Requires [`initialize_database`] first. Synchronous; errors if the update
/// fails.
Future<void> renameWallet(
        {required String currentWalletName, required String newWalletName}) =>
    RustLib.instance.api.crateApiWalletRenameWallet(
        currentWalletName: currentWalletName, newWalletName: newWalletName);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SensitiveSeeds>>
abstract class SensitiveSeeds implements RustOpaqueInterface {
  List<String> get words;

  set words(List<String> words);
}

/// The public details returned after creating, restoring, or importing a wallet.
///
/// `tari_address` is the wallet's base58 dual address. `wallet_birthday` is the
/// cipher-seed birthday (a block-height-derived epoch the scanner starts from).
/// The key hexes are the public spend key and the **private** view key. For
/// view-only imports `seed_words` is `None`; otherwise it carries the
/// **secret** [`SensitiveSeeds`] handle.
class WalletCreationDetails {
  final String tariAddress;
  final int walletBirthday;
  final String spendPublicKeyHex;
  final String viewPrivateKeyHex;
  final SensitiveSeeds? seedWords;

  const WalletCreationDetails({
    required this.tariAddress,
    required this.walletBirthday,
    required this.spendPublicKeyHex,
    required this.viewPrivateKeyHex,
    this.seedWords,
  });

  @override
  int get hashCode =>
      tariAddress.hashCode ^
      walletBirthday.hashCode ^
      spendPublicKeyHex.hashCode ^
      viewPrivateKeyHex.hashCode ^
      seedWords.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreationDetails &&
          runtimeType == other.runtimeType &&
          tariAddress == other.tariAddress &&
          walletBirthday == other.walletBirthday &&
          spendPublicKeyHex == other.spendPublicKeyHex &&
          viewPrivateKeyHex == other.viewPrivateKeyHex &&
          seedWords == other.seedWords;
}
