// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1858936417;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__wallet__create_wallet_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "create_wallet",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_network = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::wallet::create_wallet(api_network)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__db__disconnect_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "disconnect_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::db::disconnect_database()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__address__get_address_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_address",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_wallet_name = <Option<String>>::sse_decode(&mut deserializer);
            let api_passphrase = <Option<String>>::sse_decode(&mut deserializer);
            let api_network = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::address::get_address(
                            api_wallet_name,
                            api_passphrase,
                            api_network,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__balance__get_balance_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_balance",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_wallet_name = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::balance::get_balance(api_wallet_name)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__transactions__get_transactions_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_transactions",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_wallet_name = <Option<String>>::sse_decode(&mut deserializer);
            let api_limit = <i64>::sse_decode(&mut deserializer);
            let api_offset = <i64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::transactions::get_transactions(
                            api_wallet_name,
                            api_limit,
                            api_offset,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__db__initialize_database_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "initialize_database",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::db::initialize_database(api_path)?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__seeds__list_words_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "list_words",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(crate::api::seeds::list_words())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__wallet__restore_wallet_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "restore_wallet",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_seed_words = <Vec<String>>::sse_decode(&mut deserializer);
            let api_passphrase = <Option<String>>::sse_decode(&mut deserializer);
            let api_network = <Option<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::wallet::restore_wallet(
                            api_seed_words,
                            api_passphrase,
                            api_network,
                        )?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}
fn wire__crate__api__send_transaction__send_transaction_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "send_transaction",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::send_transaction::SendTransactionEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_details = <crate::api::send_transaction::SendTransactionDetails>::sse_decode(
                &mut deserializer,
            );
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::send_transaction::send_transaction(api_sink, api_details)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__scanner__start_scan_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_scan",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::scanner::ScanEventDto,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_config =
                <crate::api::scanner::ScanConfiguration>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::scanner::start_scan(api_sink, api_config).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__scanner__stop_scan_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "stop_scan",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || {
                        let output_ok = crate::api::scanner::stop_scan()?;
                        Ok(output_ok)
                    })(),
                )
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::scanner::ScanEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::send_transaction::SendTransactionEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for crate::api::balance::AccountBalanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_total = <u64>::sse_decode(deserializer);
        let mut var_unconfirmed = <u64>::sse_decode(deserializer);
        let mut var_locked = <u64>::sse_decode(deserializer);
        let mut var_available = <u64>::sse_decode(deserializer);
        return crate::api::balance::AccountBalanceDto {
            total: var_total,
            unconfirmed: var_unconfirmed,
            locked: var_locked,
            available: var_available,
        };
    }
}

impl SseDecode for crate::api::transactions::BlockchainInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_blockHeight = <u64>::sse_decode(deserializer);
        let mut var_timestamp = <String>::sse_decode(deserializer);
        let mut var_confirmations = <u64>::sse_decode(deserializer);
        return crate::api::transactions::BlockchainInfoDto {
            block_height: var_blockHeight,
            timestamp: var_timestamp,
            confirmations: var_confirmations,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::transactions::CounterpartyInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_address = <String>::sse_decode(deserializer);
        let mut var_addressEmoji = <Option<String>>::sse_decode(deserializer);
        let mut var_label = <Option<String>>::sse_decode(deserializer);
        return crate::api::transactions::CounterpartyInfoDto {
            address: var_address,
            address_emoji: var_addressEmoji,
            label: var_label,
        };
    }
}

impl SseDecode for crate::api::transactions::DisplayedTransactionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_direction = <String>::sse_decode(deserializer);
        let mut var_source = <String>::sse_decode(deserializer);
        let mut var_status = <String>::sse_decode(deserializer);
        let mut var_amount = <u64>::sse_decode(deserializer);
        let mut var_amountDisplay = <String>::sse_decode(deserializer);
        let mut var_message = <Option<String>>::sse_decode(deserializer);
        let mut var_counterparty =
            <Option<crate::api::transactions::CounterpartyInfoDto>>::sse_decode(deserializer);
        let mut var_blockchain =
            <crate::api::transactions::BlockchainInfoDto>::sse_decode(deserializer);
        let mut var_fee = <Option<crate::api::transactions::FeeInfoDto>>::sse_decode(deserializer);
        return crate::api::transactions::DisplayedTransactionDto {
            id: var_id,
            direction: var_direction,
            source: var_source,
            status: var_status,
            amount: var_amount,
            amount_display: var_amountDisplay,
            message: var_message,
            counterparty: var_counterparty,
            blockchain: var_blockchain,
            fee: var_fee,
        };
    }
}

impl SseDecode for crate::api::transactions::FeeInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_amount = <u64>::sse_decode(deserializer);
        let mut var_amountDisplay = <String>::sse_decode(deserializer);
        return crate::api::transactions::FeeInfoDto {
            amount: var_amount,
            amount_display: var_amountDisplay,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::transactions::DisplayedTransactionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(
                <crate::api::transactions::DisplayedTransactionDto>::sse_decode(deserializer),
            );
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::transactions::CounterpartyInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::transactions::CounterpartyInfoDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::transactions::FeeInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::transactions::FeeInfoDto>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::scanner::ScanConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_password = <String>::sse_decode(deserializer);
        let mut var_baseUrl = <String>::sse_decode(deserializer);
        let mut var_batchSize = <u64>::sse_decode(deserializer);
        let mut var_continuous = <bool>::sse_decode(deserializer);
        let mut var_pollIntervalSeconds = <u64>::sse_decode(deserializer);
        return crate::api::scanner::ScanConfiguration {
            password: var_password,
            base_url: var_baseUrl,
            batch_size: var_batchSize,
            continuous: var_continuous,
            poll_interval_seconds: var_pollIntervalSeconds,
        };
    }
}

impl SseDecode for crate::api::scanner::ScanEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <crate::api::scanner::ScanStatusDto>::sse_decode(deserializer);
                return crate::api::scanner::ScanEventDto::Status(var_field0);
            }
            1 => {
                let mut var_field0 =
                    <crate::api::scanner::TransactionsReadyDto>::sse_decode(deserializer);
                return crate::api::scanner::ScanEventDto::TransactionsReady(var_field0);
            }
            2 => {
                let mut var_field0 =
                    <crate::api::scanner::TransactionsUpdatedDto>::sse_decode(deserializer);
                return crate::api::scanner::ScanEventDto::TransactionsUpdated(var_field0);
            }
            3 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                return crate::api::scanner::ScanEventDto::Error(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::scanner::ScanStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_fromHeight = <u64>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::Started {
                    account_id: var_accountId,
                    from_height: var_fromHeight,
                };
            }
            1 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_currentHeight = <u64>::sse_decode(deserializer);
                let mut var_blocksScanned = <u64>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::Progress {
                    account_id: var_accountId,
                    current_height: var_currentHeight,
                    blocks_scanned: var_blocksScanned,
                };
            }
            2 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_finalHeight = <u64>::sse_decode(deserializer);
                let mut var_totalBlocksScanned = <u64>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::Completed {
                    account_id: var_accountId,
                    final_height: var_finalHeight,
                    total_blocks_scanned: var_totalBlocksScanned,
                };
            }
            3 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_lastScannedHeight = <u64>::sse_decode(deserializer);
                let mut var_reason = <String>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::Paused {
                    account_id: var_accountId,
                    last_scanned_height: var_lastScannedHeight,
                    reason: var_reason,
                };
            }
            4 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_resumeInSeconds = <u64>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::Waiting {
                    account_id: var_accountId,
                    resume_in_seconds: var_resumeInSeconds,
                };
            }
            5 => {
                let mut var_accountId = <i64>::sse_decode(deserializer);
                let mut var_lastScannedHeight = <u64>::sse_decode(deserializer);
                return crate::api::scanner::ScanStatusDto::MoreBlocksAvailable {
                    account_id: var_accountId,
                    last_scanned_height: var_lastScannedHeight,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::send_transaction::SendTransactionDetails {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_seedWords = <Vec<String>>::sse_decode(deserializer);
        let mut var_passphrase = <Option<String>>::sse_decode(deserializer);
        let mut var_network = <Option<String>>::sse_decode(deserializer);
        let mut var_baseUrl = <Option<String>>::sse_decode(deserializer);
        let mut var_walletName = <Option<String>>::sse_decode(deserializer);
        let mut var_recipientAddress = <String>::sse_decode(deserializer);
        let mut var_amount = <u64>::sse_decode(deserializer);
        let mut var_paymentId = <Option<String>>::sse_decode(deserializer);
        let mut var_confirmationWindow = <Option<u64>>::sse_decode(deserializer);
        return crate::api::send_transaction::SendTransactionDetails {
            seed_words: var_seedWords,
            passphrase: var_passphrase,
            network: var_network,
            base_url: var_baseUrl,
            wallet_name: var_walletName,
            recipient_address: var_recipientAddress,
            amount: var_amount,
            payment_id: var_paymentId,
            confirmation_window: var_confirmationWindow,
        };
    }
}

impl SseDecode for crate::api::send_transaction::SendTransactionEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_stage =
            <crate::api::send_transaction::TransactionStage>::sse_decode(deserializer);
        let mut var_details = <String>::sse_decode(deserializer);
        return crate::api::send_transaction::SendTransactionEvent {
            stage: var_stage,
            details: var_details,
        };
    }
}

impl SseDecode for crate::api::send_transaction::TransactionStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::send_transaction::TransactionStage::Initializing,
            1 => crate::api::send_transaction::TransactionStage::ValidatingInput,
            2 => crate::api::send_transaction::TransactionStage::ConnectingToNetwork,
            3 => crate::api::send_transaction::TransactionStage::FetchingBalance,
            4 => crate::api::send_transaction::TransactionStage::ConstructingTransaction,
            5 => crate::api::send_transaction::TransactionStage::SigningKeyGeneration,
            6 => crate::api::send_transaction::TransactionStage::SigningTransaction,
            7 => crate::api::send_transaction::TransactionStage::Broadcasting,
            8 => crate::api::send_transaction::TransactionStage::Completed,
            _ => unreachable!("Invalid variant for TransactionStage: {}", inner),
        };
    }
}

impl SseDecode for crate::api::scanner::TransactionsReadyDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_accountId = <i64>::sse_decode(deserializer);
        let mut var_transactions =
            <Vec<crate::api::transactions::DisplayedTransactionDto>>::sse_decode(deserializer);
        let mut var_blockHeight = <Option<u64>>::sse_decode(deserializer);
        let mut var_isInitialSync = <bool>::sse_decode(deserializer);
        return crate::api::scanner::TransactionsReadyDto {
            account_id: var_accountId,
            transactions: var_transactions,
            block_height: var_blockHeight,
            is_initial_sync: var_isInitialSync,
        };
    }
}

impl SseDecode for crate::api::scanner::TransactionsUpdatedDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_accountId = <i64>::sse_decode(deserializer);
        let mut var_updatedTransactions =
            <Vec<crate::api::transactions::DisplayedTransactionDto>>::sse_decode(deserializer);
        return crate::api::scanner::TransactionsUpdatedDto {
            account_id: var_accountId,
            updated_transactions: var_updatedTransactions,
        };
    }
}

impl SseDecode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u16::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::wallet::WalletCreationDetails {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_tariAddress = <String>::sse_decode(deserializer);
        let mut var_walletBirthday = <u16>::sse_decode(deserializer);
        let mut var_spendPublicKeyHex = <String>::sse_decode(deserializer);
        let mut var_viewPrivateKeyHex = <String>::sse_decode(deserializer);
        return crate::api::wallet::WalletCreationDetails {
            tari_address: var_tariAddress,
            wallet_birthday: var_walletBirthday,
            spend_public_key_hex: var_spendPublicKeyHex,
            view_private_key_hex: var_viewPrivateKeyHex,
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__wallet__create_wallet_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__db__disconnect_database_impl(port, ptr, rust_vec_len, data_len),
        3 => wire__crate__api__address__get_address_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__balance__get_balance_impl(port, ptr, rust_vec_len, data_len),
        5 => {
            wire__crate__api__transactions__get_transactions_impl(port, ptr, rust_vec_len, data_len)
        }
        6 => wire__crate__api__db__initialize_database_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__seeds__list_words_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__crate__api__wallet__restore_wallet_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__crate__api__send_transaction__send_transaction_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        10 => wire__crate__api__scanner__start_scan_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__scanner__stop_scan_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::balance::AccountBalanceDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.total.into_into_dart().into_dart(),
            self.unconfirmed.into_into_dart().into_dart(),
            self.locked.into_into_dart().into_dart(),
            self.available.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::balance::AccountBalanceDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::balance::AccountBalanceDto>
    for crate::api::balance::AccountBalanceDto
{
    fn into_into_dart(self) -> crate::api::balance::AccountBalanceDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::transactions::BlockchainInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.block_height.into_into_dart().into_dart(),
            self.timestamp.into_into_dart().into_dart(),
            self.confirmations.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::transactions::BlockchainInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::BlockchainInfoDto>
    for crate::api::transactions::BlockchainInfoDto
{
    fn into_into_dart(self) -> crate::api::transactions::BlockchainInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::transactions::CounterpartyInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.address.into_into_dart().into_dart(),
            self.address_emoji.into_into_dart().into_dart(),
            self.label.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::transactions::CounterpartyInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::CounterpartyInfoDto>
    for crate::api::transactions::CounterpartyInfoDto
{
    fn into_into_dart(self) -> crate::api::transactions::CounterpartyInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::transactions::DisplayedTransactionDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.direction.into_into_dart().into_dart(),
            self.source.into_into_dart().into_dart(),
            self.status.into_into_dart().into_dart(),
            self.amount.into_into_dart().into_dart(),
            self.amount_display.into_into_dart().into_dart(),
            self.message.into_into_dart().into_dart(),
            self.counterparty.into_into_dart().into_dart(),
            self.blockchain.into_into_dart().into_dart(),
            self.fee.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::transactions::DisplayedTransactionDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::DisplayedTransactionDto>
    for crate::api::transactions::DisplayedTransactionDto
{
    fn into_into_dart(self) -> crate::api::transactions::DisplayedTransactionDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::transactions::FeeInfoDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.amount.into_into_dart().into_dart(),
            self.amount_display.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::transactions::FeeInfoDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::transactions::FeeInfoDto>
    for crate::api::transactions::FeeInfoDto
{
    fn into_into_dart(self) -> crate::api::transactions::FeeInfoDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::scanner::ScanConfiguration {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.password.into_into_dart().into_dart(),
            self.base_url.into_into_dart().into_dart(),
            self.batch_size.into_into_dart().into_dart(),
            self.continuous.into_into_dart().into_dart(),
            self.poll_interval_seconds.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::scanner::ScanConfiguration
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::scanner::ScanConfiguration>
    for crate::api::scanner::ScanConfiguration
{
    fn into_into_dart(self) -> crate::api::scanner::ScanConfiguration {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::scanner::ScanEventDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::scanner::ScanEventDto::Status(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::scanner::ScanEventDto::TransactionsReady(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::scanner::ScanEventDto::TransactionsUpdated(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::scanner::ScanEventDto::Error(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::scanner::ScanEventDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::scanner::ScanEventDto>
    for crate::api::scanner::ScanEventDto
{
    fn into_into_dart(self) -> crate::api::scanner::ScanEventDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::scanner::ScanStatusDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::scanner::ScanStatusDto::Started {
                account_id,
                from_height,
            } => [
                0.into_dart(),
                account_id.into_into_dart().into_dart(),
                from_height.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::scanner::ScanStatusDto::Progress {
                account_id,
                current_height,
                blocks_scanned,
            } => [
                1.into_dart(),
                account_id.into_into_dart().into_dart(),
                current_height.into_into_dart().into_dart(),
                blocks_scanned.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::scanner::ScanStatusDto::Completed {
                account_id,
                final_height,
                total_blocks_scanned,
            } => [
                2.into_dart(),
                account_id.into_into_dart().into_dart(),
                final_height.into_into_dart().into_dart(),
                total_blocks_scanned.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::scanner::ScanStatusDto::Paused {
                account_id,
                last_scanned_height,
                reason,
            } => [
                3.into_dart(),
                account_id.into_into_dart().into_dart(),
                last_scanned_height.into_into_dart().into_dart(),
                reason.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::scanner::ScanStatusDto::Waiting {
                account_id,
                resume_in_seconds,
            } => [
                4.into_dart(),
                account_id.into_into_dart().into_dart(),
                resume_in_seconds.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::scanner::ScanStatusDto::MoreBlocksAvailable {
                account_id,
                last_scanned_height,
            } => [
                5.into_dart(),
                account_id.into_into_dart().into_dart(),
                last_scanned_height.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::scanner::ScanStatusDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::scanner::ScanStatusDto>
    for crate::api::scanner::ScanStatusDto
{
    fn into_into_dart(self) -> crate::api::scanner::ScanStatusDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::send_transaction::SendTransactionDetails {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.seed_words.into_into_dart().into_dart(),
            self.passphrase.into_into_dart().into_dart(),
            self.network.into_into_dart().into_dart(),
            self.base_url.into_into_dart().into_dart(),
            self.wallet_name.into_into_dart().into_dart(),
            self.recipient_address.into_into_dart().into_dart(),
            self.amount.into_into_dart().into_dart(),
            self.payment_id.into_into_dart().into_dart(),
            self.confirmation_window.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::send_transaction::SendTransactionDetails
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::send_transaction::SendTransactionDetails>
    for crate::api::send_transaction::SendTransactionDetails
{
    fn into_into_dart(self) -> crate::api::send_transaction::SendTransactionDetails {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::send_transaction::SendTransactionEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.stage.into_into_dart().into_dart(),
            self.details.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::send_transaction::SendTransactionEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::send_transaction::SendTransactionEvent>
    for crate::api::send_transaction::SendTransactionEvent
{
    fn into_into_dart(self) -> crate::api::send_transaction::SendTransactionEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::send_transaction::TransactionStage {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Initializing => 0.into_dart(),
            Self::ValidatingInput => 1.into_dart(),
            Self::ConnectingToNetwork => 2.into_dart(),
            Self::FetchingBalance => 3.into_dart(),
            Self::ConstructingTransaction => 4.into_dart(),
            Self::SigningKeyGeneration => 5.into_dart(),
            Self::SigningTransaction => 6.into_dart(),
            Self::Broadcasting => 7.into_dart(),
            Self::Completed => 8.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::send_transaction::TransactionStage
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::send_transaction::TransactionStage>
    for crate::api::send_transaction::TransactionStage
{
    fn into_into_dart(self) -> crate::api::send_transaction::TransactionStage {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::scanner::TransactionsReadyDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.account_id.into_into_dart().into_dart(),
            self.transactions.into_into_dart().into_dart(),
            self.block_height.into_into_dart().into_dart(),
            self.is_initial_sync.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::scanner::TransactionsReadyDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::scanner::TransactionsReadyDto>
    for crate::api::scanner::TransactionsReadyDto
{
    fn into_into_dart(self) -> crate::api::scanner::TransactionsReadyDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::scanner::TransactionsUpdatedDto {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.account_id.into_into_dart().into_dart(),
            self.updated_transactions.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::scanner::TransactionsUpdatedDto
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::scanner::TransactionsUpdatedDto>
    for crate::api::scanner::TransactionsUpdatedDto
{
    fn into_into_dart(self) -> crate::api::scanner::TransactionsUpdatedDto {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::wallet::WalletCreationDetails {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.tari_address.into_into_dart().into_dart(),
            self.wallet_birthday.into_into_dart().into_dart(),
            self.spend_public_key_hex.into_into_dart().into_dart(),
            self.view_private_key_hex.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::wallet::WalletCreationDetails
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::wallet::WalletCreationDetails>
    for crate::api::wallet::WalletCreationDetails
{
    fn into_into_dart(self) -> crate::api::wallet::WalletCreationDetails {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::scanner::ScanEventDto, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::send_transaction::SendTransactionEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for crate::api::balance::AccountBalanceDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.total, serializer);
        <u64>::sse_encode(self.unconfirmed, serializer);
        <u64>::sse_encode(self.locked, serializer);
        <u64>::sse_encode(self.available, serializer);
    }
}

impl SseEncode for crate::api::transactions::BlockchainInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.block_height, serializer);
        <String>::sse_encode(self.timestamp, serializer);
        <u64>::sse_encode(self.confirmations, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::transactions::CounterpartyInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.address, serializer);
        <Option<String>>::sse_encode(self.address_emoji, serializer);
        <Option<String>>::sse_encode(self.label, serializer);
    }
}

impl SseEncode for crate::api::transactions::DisplayedTransactionDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.direction, serializer);
        <String>::sse_encode(self.source, serializer);
        <String>::sse_encode(self.status, serializer);
        <u64>::sse_encode(self.amount, serializer);
        <String>::sse_encode(self.amount_display, serializer);
        <Option<String>>::sse_encode(self.message, serializer);
        <Option<crate::api::transactions::CounterpartyInfoDto>>::sse_encode(
            self.counterparty,
            serializer,
        );
        <crate::api::transactions::BlockchainInfoDto>::sse_encode(self.blockchain, serializer);
        <Option<crate::api::transactions::FeeInfoDto>>::sse_encode(self.fee, serializer);
    }
}

impl SseEncode for crate::api::transactions::FeeInfoDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.amount, serializer);
        <String>::sse_encode(self.amount_display, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::transactions::DisplayedTransactionDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::transactions::DisplayedTransactionDto>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::transactions::CounterpartyInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::transactions::CounterpartyInfoDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::transactions::FeeInfoDto> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::transactions::FeeInfoDto>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::scanner::ScanConfiguration {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.password, serializer);
        <String>::sse_encode(self.base_url, serializer);
        <u64>::sse_encode(self.batch_size, serializer);
        <bool>::sse_encode(self.continuous, serializer);
        <u64>::sse_encode(self.poll_interval_seconds, serializer);
    }
}

impl SseEncode for crate::api::scanner::ScanEventDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::scanner::ScanEventDto::Status(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::scanner::ScanStatusDto>::sse_encode(field0, serializer);
            }
            crate::api::scanner::ScanEventDto::TransactionsReady(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::scanner::TransactionsReadyDto>::sse_encode(field0, serializer);
            }
            crate::api::scanner::ScanEventDto::TransactionsUpdated(field0) => {
                <i32>::sse_encode(2, serializer);
                <crate::api::scanner::TransactionsUpdatedDto>::sse_encode(field0, serializer);
            }
            crate::api::scanner::ScanEventDto::Error(field0) => {
                <i32>::sse_encode(3, serializer);
                <String>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::scanner::ScanStatusDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::scanner::ScanStatusDto::Started {
                account_id,
                from_height,
            } => {
                <i32>::sse_encode(0, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(from_height, serializer);
            }
            crate::api::scanner::ScanStatusDto::Progress {
                account_id,
                current_height,
                blocks_scanned,
            } => {
                <i32>::sse_encode(1, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(current_height, serializer);
                <u64>::sse_encode(blocks_scanned, serializer);
            }
            crate::api::scanner::ScanStatusDto::Completed {
                account_id,
                final_height,
                total_blocks_scanned,
            } => {
                <i32>::sse_encode(2, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(final_height, serializer);
                <u64>::sse_encode(total_blocks_scanned, serializer);
            }
            crate::api::scanner::ScanStatusDto::Paused {
                account_id,
                last_scanned_height,
                reason,
            } => {
                <i32>::sse_encode(3, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(last_scanned_height, serializer);
                <String>::sse_encode(reason, serializer);
            }
            crate::api::scanner::ScanStatusDto::Waiting {
                account_id,
                resume_in_seconds,
            } => {
                <i32>::sse_encode(4, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(resume_in_seconds, serializer);
            }
            crate::api::scanner::ScanStatusDto::MoreBlocksAvailable {
                account_id,
                last_scanned_height,
            } => {
                <i32>::sse_encode(5, serializer);
                <i64>::sse_encode(account_id, serializer);
                <u64>::sse_encode(last_scanned_height, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::send_transaction::SendTransactionDetails {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.seed_words, serializer);
        <Option<String>>::sse_encode(self.passphrase, serializer);
        <Option<String>>::sse_encode(self.network, serializer);
        <Option<String>>::sse_encode(self.base_url, serializer);
        <Option<String>>::sse_encode(self.wallet_name, serializer);
        <String>::sse_encode(self.recipient_address, serializer);
        <u64>::sse_encode(self.amount, serializer);
        <Option<String>>::sse_encode(self.payment_id, serializer);
        <Option<u64>>::sse_encode(self.confirmation_window, serializer);
    }
}

impl SseEncode for crate::api::send_transaction::SendTransactionEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <crate::api::send_transaction::TransactionStage>::sse_encode(self.stage, serializer);
        <String>::sse_encode(self.details, serializer);
    }
}

impl SseEncode for crate::api::send_transaction::TransactionStage {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::send_transaction::TransactionStage::Initializing => 0,
                crate::api::send_transaction::TransactionStage::ValidatingInput => 1,
                crate::api::send_transaction::TransactionStage::ConnectingToNetwork => 2,
                crate::api::send_transaction::TransactionStage::FetchingBalance => 3,
                crate::api::send_transaction::TransactionStage::ConstructingTransaction => 4,
                crate::api::send_transaction::TransactionStage::SigningKeyGeneration => 5,
                crate::api::send_transaction::TransactionStage::SigningTransaction => 6,
                crate::api::send_transaction::TransactionStage::Broadcasting => 7,
                crate::api::send_transaction::TransactionStage::Completed => 8,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::scanner::TransactionsReadyDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.account_id, serializer);
        <Vec<crate::api::transactions::DisplayedTransactionDto>>::sse_encode(
            self.transactions,
            serializer,
        );
        <Option<u64>>::sse_encode(self.block_height, serializer);
        <bool>::sse_encode(self.is_initial_sync, serializer);
    }
}

impl SseEncode for crate::api::scanner::TransactionsUpdatedDto {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i64>::sse_encode(self.account_id, serializer);
        <Vec<crate::api::transactions::DisplayedTransactionDto>>::sse_encode(
            self.updated_transactions,
            serializer,
        );
    }
}

impl SseEncode for u16 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u16::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::wallet::WalletCreationDetails {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.tari_address, serializer);
        <u16>::sse_encode(self.wallet_birthday, serializer);
        <String>::sse_encode(self.spend_public_key_hex, serializer);
        <String>::sse_encode(self.view_private_key_hex, serializer);
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
